version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres1"
    ports:
      - "5433:5432"
    volumes:
      - my_dbdata_1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
  db2:
    image: "postgres:11"
    container_name: "my_postgres2"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata_2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
  airflow:
    image: puckel/docker-airflow
    container_name: "airflow2"
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/usr/local/airflow/
    volumes:
      - ./operators:/usr/local/airflow/operators
      - ./dags/:/usr/local/airflow/dags
    command: webserver
volumes:
  my_dbdata_1:
  my_dbdata_2: